@baseUrl = http://127.0.0.1:8000

### Register Responder 1
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "email": "responder@email.com",
  "password": "123456",
  "password_confirmation": "123456"
}

### Register Responder 2
POST {{baseUrl}}/api/register
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456",
  "password_confirmation": "123456"
}

### Login Responder 1
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "responder@email.com",
  "password": "123456"
}

### Login Responder 2
# @name login
POST {{baseUrl}}/api/login
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "123456"
}

###
@authToken = {{login.response.body.token}}

### Logout Responder
GET {{baseUrl}}/api/logout
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Responder Informations
GET {{baseUrl}}/api/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get active surveys
GET {{baseUrl}}/api/surveys
Content-Type: application/json

### Get specific survey with questions.
GET {{baseUrl}}/api/surveys/2
Content-Type: application/json

### Submit answers to a survey - created
POSt {{baseUrl}}/api/surveys/1/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "answers": [
    {
      "question_id": "1",
      "value": "string"
    },
    {
      "question_id": "2",
      "value": [ 1, 4, 6 ]
    }
  ]
}

### Submit answers to a survey - validation errors (duplicate value)
POSt {{baseUrl}}/api/surveys/1/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "answers": [
    {
      "question_id": 1,
      "value": "string"
    },
    {
      "question_id": 1,
      "value": [ 1, 4, 6 ]
    }
  ]
}

### Submit answers to a survey - survey not exist
POSt {{baseUrl}}/api/surveys/2/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "answers": [
    {
      "question_id": 3,
      "value": "string"
    },
    {
      "question_id": 4,
      "value": [ 1, 4, 6 ]
    }
  ]
}

### Submit answers to a survey - unsupported type
POSt {{baseUrl}}/api/surveys/1/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "answers": [
    {
      "question_id": 1,
      "value": [ 1, 4, 6 ]
    },
    {
      "question_id": 2,
      "value": "string"
    }
  ]
}

### Submit answers to a survey - question not found in survey
POSt {{baseUrl}}/api/surveys/1/submit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "answers": [
    {
      "question_id": 3,
      "value": "string"
    },
    {
      "question_id": 2,
      "value": [ 1, 4, 6 ]
    }
  ]
}